"""add many-to-many between videos and categories

Revision ID: 874fdb0cd607
Revises: 7a1eee2342bc
Create Date: 2025-07-31 08:16:27.348360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874fdb0cd607'
down_revision: Union[str, Sequence[str], None] = '7a1eee2342bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
